version: 2.1

description: Tasks for integrating the Boxt Rubocop style guide

display:
  home_url: "https://github.com/boxt/orbs"
  source_url: "https://github.com/boxt/rubocop-orb/blob/master/config.yml"

commands:
  lint:
    description: Run the linter against changes made on the current branch
    steps:
      - run:
          name: "Run lint:rubocop against the git diff"
          command: |
            git checkout -q $CIRCLE_BRANCH
            bundle exec rake lint:rubocop
