version: 2.1

description: Tasks for integrating Boxt's RuboCop style guide

display:
  home_url: "https://github.com/boxt/orbs"
  source_url: "https://github.com/boxt/rubocop-orb/blob/main/config.yml"

commands:
  lint:
    description: Run rubocop against the codebase
    steps:
      - run:
          name: "Run RuboCop"
          command: bundle exec rubocop
